### ISSUE TITLE
Cannot use functions of the Monaco API

### ISSUE THREAD

**Issue by DrNiels** [PolymerVis/monaco-editor#5]
As far as I understand, I should be able to access the Monaco API with the monaco attribute. However, when I call a function, e.g.,
`this.$['editor'].monaco.languages.registerCompletionItemProvider(...)`, an error occurs, stating the function does not exist. Using a console.log shows me that the function is undefined.

**Comment by eterna2** [comment]
You can't because the monaco and editor instances are proxy to the real monaco and editor in the iframe.

Monaco editor makes use of some global scope APIs that are not available in the shadowRoot, hence, will not work in a webcomponent.

To overcome this, what the monaco-editor element does is to create the editor inside an iframe. 

An iframe means u cannot access the editor or monaco instances directly. Hence, I created a proxy to the iframe. However, only selected functions are proxied. 

It will be alot harder to proxy a function over, unless u write it as a separate js file, and we load it in the iframe.

If u tell me what are the functions u need, I see if I can device a method to access these functions. But note that all function calls will be asynchronous aka return a promise becuz we need to proxy to the iframe.

**Comment by DrNiels** [comment]
I didn't expect this to be that complicated. Unfortunately, I don't know which functions I need exactly. 

My main goal here is to provide auto-completion for a PHP editor with custom commands.

Maybe you can show me an example how you proxied a function? Then I could branch your repository and implement the functions while discovering which ones I need. 

When I'm done, I'd create a pull request, so you can provide access to these functions from the main repository as well.

**Comment by eterna2** [comment]
@DrNiels 

You can look at https://github.com/PolymerVis/monaco-editor/blob/master/monaco-editor-iframe.js

This is the codes where we create a "virtual" monaco and editor instance. As well as the iframe codes.

**Comment by eterna2** [comment]
For example, look at this snippet of MonacoProxy:

when u execute `monaco.languages.json.jsonDefaults.setDiagnosticsOptions`, it returns u a `function`.

Instead of the actual monaco function, this function post a message to the iframe.

Correspondingly, the iframe will listen for this message and call the "real" monaco function with the provided arguments.

```js
  class MonacoProxy {
    constructor(iframe, editorReference) {
      this._iframe_ = iframe;
      this._editorReference_ = editorReference;
      this.languages.json.jsonDefaults.setDiagnosticsOptions;
    }
    get languages() {
      return {
        json: {
          jsonDefaults: {
            setDiagnosticsOptions: opts => {
              this.postMessage({
                path: ['monaco', 'languages', 'json', 'jsonDefaults'],
                event: 'setDiagnosticsOptions',
                args: [opts]
              });
            }
          }
        }
      };
    }
    postMessage(msg) {
      msg.editorReference = this._editorReference_;
      this._iframe_.contentWindow.postMessage(msg, document.location.href);
    }
   ...
```

**Comment by DrNiels** [comment]
Thanks for the hints! Initial experiments are working fine. I'll share them with you via pull request once they matured a bit more.

**Comment by DrNiels** [comment]
I made the first pull request with functions for providing auto completion. If I find further functions that I need, I'll just keep making pull requests. Thanks again!
